### ISSUE TITLE
Signer info does not persist 

### ISSUE THREAD

**Issue by orangesurf** [mycitadel/mycitadel-desktop#37] opened 2022-05-04 20:13 UTC
## Bug type
Put `x` in the boxes below:
- [ ] Installation issue
- [ ] App crash
- [ ] Broken UI
- [x] Incorrect app behaviour

## Operating system
- [x] Linux (Pop!_OS 22.04 LTS)
- [ ] MacOS
- [ ] Windows

## Problem description
Changes to signer information (for example changing m/0h/0h to m/84h/0h/0h) do not persist when a different signer is selected.

How to reproduce:
1. Make a new wallet
2. Add 2 xpub signers
3. Select first signer from signers tab
4. Enter a name (xpub1) in the name field
5. Select the second signer (xpub1 name is correctly shown in signer summary table at top)
6. Enter name (xpub2) in the name field 
7. Click on the first signer 
8. The name field is blank - This is unexpected
9. Change the Origin to m/84h/0h/0h and click anywhere on screen
10. Name of the first signer in list is made blank

**Comment by dr-orlovsky** [comment] 2022-05-05 08:01
Working on fix

**Comment by dr-orlovsky** [comment] 2022-05-14 09:37
Should be fixed with [v1.1 release](https://github.com/mycitadel/mycitadel-desktop/releases/tag/v1.1.0) but not 100% sure since I was not able to reproduce the issue

**Comment by dr-orlovsky** [comment] 2023-04-13 14:11
Not actually fixed

**Comment by dr-orlovsky** [comment] 2023-04-21 11:48
The investigation shows that the bug occurs only for hardware devices: in fact, for any hardware device any edits to the signer name get reverted back to the devince name the moment the control is updated; i.e. they do not persist into the model (or get rewritten on the model updates).

**Comment by dr-orlovsky** [comment] 2023-04-22 09:39
Further investigation has show that https://github.com/mycitadel/mycitadel-desktop/issues/37#issuecomment-1517704225 is not the case.

Signer names do not persist only on certain machines - behaving normally in all other cases. This is not linked to the use of hardware signers nor specific OS version.

**Comment by dr-orlovsky** [comment] 2023-07-11 05:09
It happens only when a release build is used (but not on debug builds)

**Closed** 2023-07-11 05:18 UTC
Labels: C-bug, W-settings, C-important
